# Getting Started with GitHub Actions

# This repository will be used to get started with GitHub Actions!

name: First Workflow
on: workflow_dispatch
jobs: 
    marcus-first-job:
        runs-on: ubuntu-latest
        steps: 
            - name: Print Hello World
              run: echo "Hello World"
            - name: Print goodbye
              run: echo "Done - bye"
